name: Build with ESP-IDF v4.1

on: [push]

jobs:
  builder:
    name: Builder for ESP32BoardManager example application
    runs-on: ubuntu-20.04

    env:
      main-path: app
      app-path: app/example
      out-file: Example-ESP32BoardManager

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.main-path }}

      - name: Create the code library
        run: |
          mkdir -p "${{ github.workspace }}/lib/ESP32"
          cd "${{ github.workspace }}/lib/ESP32"
          git clone --depth 1 https://github.com/CalinRadoni/ESP32BoardManager.git
          git clone --depth 1 https://github.com/CalinRadoni/ESP32SimpleOTA.git
          git clone --depth 1 https://github.com/CalinRadoni/ESP32HAL.git

      - name: Action execution
        uses: CalinRadoni/esp-idf-v4-container-action@v4.1
        id: execution
        with:
          entrypoint: /github/workspace/${{ env.app-path }}/action-build.sh

      - name: Compute SHA256 for bin and elf files
        if: steps.execution.outputs.result == 0
        run: |
          file="${{ github.workspace }}/${{ env.app-path }}/build/${{ env.out-file }}.bin"
          hash=$(sha256sum -b "$file")
          stat -c"$hash %s" "$file"
          file="${{ github.workspace }}/${{ env.app-path }}/build/${{ env.out-file }}.elf"
          hash=$(sha256sum -b "$file")
          stat -c"$hash %s" "$file"
