name: Build with ESP-IDF v4.1

on: [push]

jobs:
  builder:
    name: Builder for ESP32BoardManager example application
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: app

      - name: Create the code library
        run: |
          mkdir -p "${{ github.workspace }}/lib/ESP32"
          cd "${{ github.workspace }}/lib/ESP32"
          git clone --depth 1 https://github.com/CalinRadoni/ESP32BoardManager.git
          git clone --depth 1 https://github.com/CalinRadoni/ESP32SimpleOTA.git
          git clone --depth 1 https://github.com/CalinRadoni/ESP32HAL.git

      - name: Action execution
        uses: CalinRadoni/esp-idf-v4-container-action@v4.1
        id: execution
        with:
          entrypoint: /github/workspace/app/example/action-build.sh

      - name: Compute SHA256 for bin and elf files
        if: steps.execution.outputs.result == 0
        run: |
          sha256sum -b "${{ github.workspace }}/app/example/build/Example-ESP32BoardManager.bin"
          sha256sum -b "${{ github.workspace }}/app/example/build/Example-ESP32BoardManager.elf"
